### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by jonnahmarie** [RickyBlaze100/PlantyFeelzDatabase.github.io#4]
create schema for the database

[DBMS ER diagram (UML notation).pdf]

User Story
AS AN a user with a desire to learn more about plants
I WANT to be able to query a plant database
SO THAT I could find plants that interest me

Acceptance Criteria
GIVEN a UML diagram
WHEN I query the PLANT table
THEN I am presented with ID(PK), Name, Genus(FK), and Maintenance (FK) fields
WHEN I query the MAINTENANCE table
THEN I am presented with ID(PK), Water, Temperature, Light, Humidity, and Soil fields
WHEN I query the GENUS table
THEN I am presented with the ID(PK), and various genus types

UML provided:
(https://github.com/RickyBlaze100/PlantyFeelzDatabase.github.io/files/5898736/DBMS.ER.diagram.UML.notation.pdf)

**Comment by vtaymany** [comment]
[DBMS ER diagram (UML notation).pdf]

**User Story**
AS AN a user with a desire to learn more about plants
I WANT to be able to query a plant database
SO THAT I could find plants that interest me

**Acceptance Criteria**
GIVEN a UML diagram
WHEN I query the PLANT table
THEN I am presented with ID(PK), Name, Genus(FK), and Maintenance (FK) fields
WHEN I query the MAINTENANCE table
THEN I am presented with ID(PK), Water, Temperature, Light, Humidity, and Soil fields
WHEN I query the GENUS table
THEN I am presented with the ID(PK), and varius genus types

UML provided:
(https://github.com/RickyBlaze100/PlantyFeelzDatabase.github.io/files/5898736/DBMS.ER.diagram.UML.notation.pdf)

**Comment by JadeP27** [comment]
Used MYSQLworkbench to create the Botani_dex database.
Created the 3 tables for Plants, Genus, and Maintenance including all necessary fields.
Also researched information for the example genus seeds file...

  dracaena,
  begonia,
  alocasia,
  yucca,
  maranta,
  violet,
  lily,
  orchids,
  calathea,
  rosa
